- hosts: 192.168.18.200
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: localhost.localdomain
    vcenter_username: root
    vcenter_password: redhat!1234
    esxi_hostname: it22-server

  tasks:
    - name: Create a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /
        name: 2-Iaac-Ansible-VM
        state: poweredon
        guest_id: fedora64Guest
        esxi_hostname: "{{ esxi_hostname }}"
        disk:
          - size_gb: 40
            type: thick
            datastore: datastore1
        hardware:
          memory_mb: 4000
          num_cpus: 4
          scsi: paravirtual
        cdrom:
          controller_number: 0
          unit_number: 0
          controller_type: sata
          state: present
          type: iso
          iso_path: '[datastore1]/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso'
          datastore: datastore1
        networks:
          - name: VM Network
            mac: aa:bb:dd:aa:00:14
            ip: 10.10.10.100
            netmask: 255.255.255.0
            device_type: vmxnet3
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 600
      delegate_to: localhost
      register: deploy_vm
