---
- name: Check SSL certificate expiry date and send emails
  hosts: localhost
  gather_facts: yes
  vars:
    domains:
      - "aap.it22.cloud"  # Replace with your list of domains
      - "console-openshift-console.apps.alpha.it22.cloud"
      - "it22.nl"
      - "it22.uk"
      - "www.it22.nl"
      - "www.it22.uk"
  tasks:
    - name: Import Python datetime module
      ansible.builtin.shell: echo "from datetime import datetime, timedelta" > /tmp/datetime_import.py
      args:
        creates: /tmp/datetime_import.py
      run_once: true
    
    - name: Include Python datetime module
      ansible.builtin.shell: python /tmp/datetime_import.py
      run_once: true
    - name: Loop through domains and get SSL certificate expiry
      include_tasks: modified.yaml 
      with_items: "{{ domains }}"
